 #-*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chat_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from client import *
from PyQt5.QtCore import QThread, pyqtSignal
from threading import Thread
from time import sleep


class Ui_MainWindow(object):
    def __init__(self):
        self.cnt=0
        self.cnt_for_scroll=0
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(796, 850)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0.169154 rgba(255, 255, 255, 255), stop:0.810945 rgba(231, 231, 231, 255));")
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-1, -1, 801, 851))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.scrollArea = QtWidgets.QScrollArea(self.frame)
        self.scrollArea.setGeometry(QtCore.QRect(178, 44, 621, 767))
        self.scrollArea.setStyleSheet("background-color: rgb(255, 244, 229);")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 598, 852))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(200, 852))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.MessageEntry = QtWidgets.QLineEdit(self.frame)
        self.MessageEntry.setGeometry(QtCore.QRect(178, 810, 621, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.MessageEntry.setFont(font)
        self.MessageEntry.setStyleSheet("background-color: white\n"
"")
        self.MessageEntry.setObjectName("MessageEntry")
        self.SearchLine = QtWidgets.QLineEdit(self.frame)
        self.SearchLine.setGeometry(QtCore.QRect(0, 0, 179, 41))
        self.SearchLine.setStyleSheet("background-color: white")
        self.SearchLine.setObjectName("SearchLine")
        self.SendButton = QtWidgets.QPushButton(self.frame)
        self.SendButton.clicked.connect(self.send)
        self.SendButton.setGeometry(QtCore.QRect(740, 810, 61, 41))
        self.SendButton.setStyleSheet(" background-color: transparent\n"
"")
        self.SendButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons8--96.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SendButton.setIcon(icon)
        self.SendButton.setIconSize(QtCore.QSize(50, 50))
        self.SendButton.setObjectName("SendButton")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.frame)
        self.scrollArea_2.setGeometry(QtCore.QRect(0, 40, 181, 811))
        self.scrollArea_2.setStyleSheet("background-color: rgb(255, 249, 244);")
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 158, 859))
        self.scrollAreaWidgetContents_2.setMinimumSize(QtCore.QSize(0, 859))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.Chat_1Button = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.Chat_1Button.setGeometry(QtCore.QRect(0, 10, 161, 28))
        self.Chat_1Button.setStyleSheet("background-color: transparent")
        self.Chat_1Button.setObjectName("Chat_1Button")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(180, 40, 621, 5))
        self.line.setStyleSheet("background-color:black")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(180, 0, 621, 41))
        self.frame_2.setStyleSheet("background-color: rgb(255, 249, 244);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.OpponentName = QtWidgets.QLabel(self.frame_2)
        self.OpponentName.setGeometry(QtCore.QRect(20, -1, 581, 41))
        self.OpponentName.setObjectName("OpponentName")
        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.pidor = Pidor(parent=None)
        self.pidor.start()
        self.pidor.signal.connect(self.New_Message)




    def New_Message(self, i):
        font = QtGui.QFont()
        font.setPointSize(11)
        mess=i[:-1]
        user=i[-1]
        print(user)
        if self.cnt >= 25:
            self.cnt_for_scroll += 1
            self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(200, 852 + 30 * self.cnt_for_scroll))
        self.MesLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.MesLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.MesLabel.setGeometry(QtCore.QRect(420, 20 + self.cnt*30, 161, 21))
        self.MesLabel.setAlignment(QtCore.Qt.AlignRight)
        self.MesLabel.setFont(font)
        self.MesLabel.setText(mess)
        self.MesLabel.show()
        self.cnt += 1

    def send(self):
        mes = self.MessageEntry.text()+'1'
        self.New_Message(mes)
        sc.send(mes.encode())




    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Chat_1Button.setText(_translate("MainWindow", "Чат 1"))
        self.OpponentName.setText(_translate("MainWindow", "Имя собеседника"))


class Pidor(QThread):
    signal= pyqtSignal(str)
    def __init__(self, parent=None):
        super(QThread, self).__init__(parent)

    def run(self):
        while True:
            mess=sc.recv(1024)
            print(mess.decode())
            try:
                self.signal.emit(mess.decode())
            except Exception as ex:
                print(ex)


history = ['mes1', 'mes2', 'msdfsdfdsfsdfes3']
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()

    sys.exit(app.exec_())
